### ISSUE TITLE
MIMIC-III data generation

### ISSUE THREAD

**Issue by ellen-ejkim** [JonathanCrabbe/Dynamask#2]
Hi!

I am trying to reproduce your experiment on MIMIC-III dataset.

Following your instruction, I ran the following command.

> python data_generator/icu_mortality.py

To be precise, I fix it as follows because icu_mortaility.py exists in fit/data_generator.

> python fit/data_generator/icu_mortality.py

But, it produced not 'patient_vital_preprocessed.pkl' but 'adult_icu_vital.gz' and 'adult_icu_lab.gz'.

How can I generate 'patient_vital_preprocessed.pkl'?

Thanks!

**Comment by JonathanCrabbe** [comment]
Hi Ellen,

Thanks for pointing this out!

You are indeed right: there is a script to preprocess the data that is missing.
I have added this file and updated the instructions accordingly in the last version.
Hopefully, everything works properly now :)

Best,
Jonathan
